// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::{METHOD_ELF, METHOD_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};
use std::io::Write;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let current_dir = std::path::PathBuf::from(args[1].clone());

    // INPUT //

    let env = ExecutorEnv::builder().build().unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Produce a receipt by proving the specified ELF binary.
    let receipt = prover.prove(env, METHOD_ELF).unwrap().receipt;

    receipt.verify(METHOD_ID).unwrap();

    // OUTPUT //

    let serialized = bincode::serialize(&receipt).unwrap();

    //TODO(pat): remove expects
    std::fs::create_dir_all(current_dir.join("proof_data/risc0")).expect("Failed to create proof_data/sp1");
    std::fs::write(&current_dir.join("proof_data/risc0/risc0.proof"), &serialized).expect("Failed to create Risc0 proof file");
    std::fs::write(&current_dir.join("proof_data/risc0/risc0.imageid"), &convert(&METHOD_ID)).expect("Failed to create Risc0 Image ID file");
    std::fs::write(&current_dir.join("proof_data/risc0/risc0.pub"), &receipt.journal.bytes).expect("Failed to create Risc0 public input file");
}

pub fn convert(data: &[u32; 8]) -> [u8; 32] {
    let mut res = [0; 32];
    for i in 0..8 {
        res[4 * i..4 * (i + 1)].copy_from_slice(&data[i].to_le_bytes());
    }
    res
}
